### ISSUE TITLE
UserController_EndpointTestFailure_

### ISSUE THREAD

**Issue by Manaswi15** [schandrakandi/Trello_quora#22]
-------------------------------------------------------------------------------
Test set: com.upgrad.quora.api.controller.UserControllerTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.622 s <<< FAILURE! - in com.upgrad.quora.api.controller.UserControllerTest
signoutWithNonExistingAccessToken(com.upgrad.quora.api.controller.UserControllerTest)  Time elapsed: 1.505 s  <<< FAILURE!
java.lang.AssertionError: Status expected:<401> but was:<404>
	at com.upgrad.quora.api.controller.UserControllerTest.signoutWithNonExistingAccessToken(UserControllerTest.java:45)

**Comment by schandrakandi** [comment]
This is Fixed with latest code.
